### ISSUE TITLE
Not able to generate execitable

### ISSUE THREAD

**Issue by blackvirus18** [gnewton/chidley#10]
Hi Team,

Can you please guide me how to generate an executable for this.
When I am running go build chidley.go I am getting following errors.

# command-line-arguments
./chidley.go:50: undefined: PrintGoStructVisitor
./chidley.go:234: undefined: Node
./chidley.go:234: undefined: FQN
./chidley.go:268: undefined: FQN
./chidley.go:315: undefined: Source
./chidley.go:378: undefined: XMLType
./chidley.go:378: undefined: Node
./chidley.go:398: undefined: Node
./chidley.go:406: undefined: PrintGoStructVisitor
./chidley.go:406: too many errors

**Comment by gnewton** [comment]
Instead of 
`go build chidley.go`
please use:
`go build`
