### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by suntong** [gnewton/chidley#12]
Hi @gnewton, would parsing JSON more difficult than parsing XML? Is you internal structure for parsed XML make it easy to accept JSON as the source as well? 

The reason I'm asking is that, of all JSON to Go Struct packages that I found, all of them has limitations [1] that made them impractical to be used, which after years haven't been fixed. 

Thus I'm hoping you will extend chidley to support JSON someday. Thx. 

[1] github.com/ChimeraCoder/gojson/issues/14

**Comment by suntong** [comment]
Hi, 

I'm going to look into it, and only 

`-G, structsToStdout, "Only write generated Go structs to stdout"
`

will be supported as the first step. 

If I made it, and provided that the code is good, would you accept the PR?

**Comment by gnewton** [comment]
I do not think I want to undertake JSON for this application.
