### ISSUE TITLE
Duplicate struct field generation

### ISSUE THREAD

**Issue by klauern** [gnewton/chidley#14]
I have a snippet of XML that does something weird with the generated struct:

```xml
<con1:actions>
   <con2:route xmlns:con2="http://www.bea.com/wli/sb/stages/routing/config">
     <con3:id xmlns:con3="http://www.bea.com/wli/sb/stages/config">_ActionId-3525062221263473230--64db5972.154ce25275c.-7fc5</con3:id>
     <con2:service ref="Something/Proxy/Something" xsi:type="ref:ProxyRef" xmlns:ref="http://www.bea.com/wli/sb/reference" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
     <con2:operation passThrough="true"/>
     <con2:outboundTransform/>
     <con2:responseTransform/>
   </con2:route>
</con1:actions>
```

Generates this struct, with the duplicated `Attr_ref` field:
```go
type Chicon2_service struct {
	Attr_ref      string   `xml:" ref,attr"  json:",omitempty"`
	Attr_ref      string   `xml:"xmlns ref,attr"  json:",omitempty"`
	Attr_xsi_type string   `xml:"http://www.w3.org/2001/XMLSchema-instance type,attr"  json:",omitempty"`
	Attr_xsi      string   `xml:"xmlns xsi,attr"  json:",omitempty"`
	XMLName       xml.Name `xml:"http://www.bea.com/wli/sb/stages/routing/config service,omitempty" json:"service,omitempty"`
}
```

**Comment by klauern** [comment]
So it looks like it boils down to that one `con2:service` node, and inferring what it's generating for the others, I would think that 

```xml
<con2:service ref="Something/Proxy/Something" xsi:type="ref:ProxyRef" xmlns:ref="http://www.bea.com/wli/sb/reference" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
```

The `xmlns:ref` field should be:

```go
Attr_xmlns_ref     string   `xml:"xmlns ref,attr"  json:",omitempty"`
```

**Comment by klauern** [comment]
Here's a full example of the issue, so it's either an invalid `struct` definition, or there's something incorrect in the XML.

https://play.golang.org/p/HvRlIitu59

**Comment by gnewton** [comment]
Yes, I think I know why this is happening. I will look in to it.

**Comment by gnewton** [comment]
This now works properly. It appends the namespace to the name after 2 underscores. This is the output from your problematic XML:


    
    type ChiChidleyRoot314159 struct {
    	Chiactions *Chiactions `xml:"con1 actions,omitempty" json:"actions,omitempty"`
    }
    
    type Chiactions struct {
    	Chiroute__con2 *Chiroute__con2 `xml:"http://www.bea.com/wli/sb/stages/routing/config route,omitempty" json:"route,omitempty"`
    	XMLName  xml.Name `xml:"con1 actions,omitempty" json:"actions,omitempty"`
    }
    
    type Chiid__con3 struct {
    	AttrXmlnscon3 string`xml:"xmlns con3,attr"  json:",omitempty"`  // maxLength=39
    	Text string `xml:",chardata" json:",omitempty"`   // maxLength=57
    	XMLName  xml.Name `xml:"http://www.bea.com/wli/sb/stages/config id,omitempty" json:"id,omitempty"`
    }
    
    type Chioperation__con2 struct {
    	AttrpassThrough string`xml:"passThrough,attr"  json:",omitempty"`  // maxLength=4
    	XMLName  xml.Name `xml:"http://www.bea.com/wli/sb/stages/routing/config operation,omitempty" json:"operation,omitempty"`
    }
    
    type ChioutboundTransform__con2 struct {
    	XMLName  xml.Name `xml:"http://www.bea.com/wli/sb/stages/routing/config outboundTransform,omitempty" json:"outboundTransform,omitempty"`
    }
    
    type ChiresponseTransform__con2 struct {
    	XMLName  xml.Name `xml:"http://www.bea.com/wli/sb/stages/routing/config responseTransform,omitempty" json:"responseTransform,omitempty"`
    }
    
    type Chiroute__con2 struct {
    	AttrXmlnscon2 string`xml:"xmlns con2,attr"  json:",omitempty"`  // maxLength=47
    	Chiid__con3 *Chiid__con3 `xml:"http://www.bea.com/wli/sb/stages/config id,omitempty" json:"id,omitempty"`
    	Chioperation__con2 *Chioperation__con2 `xml:"http://www.bea.com/wli/sb/stages/routing/config operation,omitempty" json:"operation,omitempty"`
    	ChioutboundTransform__con2 *ChioutboundTransform__con2 `xml:"http://www.bea.com/wli/sb/stages/routing/config outboundTransform,omitempty" json:"outboundTransform,omitempty"`
    	ChiresponseTransform__con2 *ChiresponseTransform__con2 `xml:"http://www.bea.com/wli/sb/stages/routing/config responseTransform,omitempty" json:"responseTransform,omitempty"`
    	Chiservice__con2 *Chiservice__con2 `xml:"http://www.bea.com/wli/sb/stages/routing/config service,omitempty" json:"service,omitempty"`
    	XMLName  xml.Name `xml:"http://www.bea.com/wli/sb/stages/routing/config route,omitempty" json:"route,omitempty"`
    }
    
    type Chiservice__con2 struct {
    	Attrref string`xml:"ref,attr"  json:",omitempty"`  // maxLength=25
    	AttrXmlnsref string`xml:"xmlns ref,attr"  json:",omitempty"`  // maxLength=35
    	AttrXsiSpacetype string`xml:"http://www.w3.org/2001/XMLSchema-instance type,attr"  json:",omitempty"`  // maxLength=12
    	AttrXmlnsxsi string`xml:"xmlns xsi,attr"  json:",omitempty"`  // maxLength=41
    	XMLName  xml.Name `xml:"http://www.bea.com/wli/sb/stages/routing/config service,omitempty" json:"service,omitempty"`
    }
